"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Gender:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _GenderEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Gender.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    GENDER_UNSPECIFIED: _Gender.ValueType  # 0
    GENDER_MALE: _Gender.ValueType  # 1
    GENDER_FEMALE: _Gender.ValueType  # 2

class Gender(_Gender, metaclass=_GenderEnumTypeWrapper): ...

GENDER_UNSPECIFIED: Gender.ValueType  # 0
GENDER_MALE: Gender.ValueType  # 1
GENDER_FEMALE: Gender.ValueType  # 2
Global___Gender: typing_extensions.TypeAlias = Gender

class _GenderPref:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _GenderPrefEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_GenderPref.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    GENDER_PREF_UNSPECIFIED: _GenderPref.ValueType  # 0
    GENDER_PREF_MALE: _GenderPref.ValueType  # 1
    GENDER_PREF_FEMALE: _GenderPref.ValueType  # 2
    GENDER_PREF_ANY: _GenderPref.ValueType  # 3

class GenderPref(_GenderPref, metaclass=_GenderPrefEnumTypeWrapper): ...

GENDER_PREF_UNSPECIFIED: GenderPref.ValueType  # 0
GENDER_PREF_MALE: GenderPref.ValueType  # 1
GENDER_PREF_FEMALE: GenderPref.ValueType  # 2
GENDER_PREF_ANY: GenderPref.ValueType  # 3
Global___GenderPref: typing_extensions.TypeAlias = GenderPref

@typing.final
class HealthRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___HealthRequest: typing_extensions.TypeAlias = HealthRequest

@typing.final
class HealthResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OK_FIELD_NUMBER: builtins.int
    ok: builtins.bool
    def __init__(
        self,
        *,
        ok: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ok", b"ok"]) -> None: ...

Global___HealthResponse: typing_extensions.TypeAlias = HealthResponse

@typing.final
class CreateProfileRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TELEGRAM_ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    AGE_FIELD_NUMBER: builtins.int
    CITY_FIELD_NUMBER: builtins.int
    BIO_FIELD_NUMBER: builtins.int
    GENDER_FIELD_NUMBER: builtins.int
    LATITUDE_FIELD_NUMBER: builtins.int
    LONGITUDE_FIELD_NUMBER: builtins.int
    telegram_id: builtins.int
    name: builtins.str
    age: builtins.int
    city: builtins.str
    bio: builtins.str
    gender: Global___Gender.ValueType
    latitude: builtins.float
    longitude: builtins.float
    def __init__(
        self,
        *,
        telegram_id: builtins.int = ...,
        name: builtins.str = ...,
        age: builtins.int = ...,
        city: builtins.str = ...,
        bio: builtins.str = ...,
        gender: Global___Gender.ValueType = ...,
        latitude: builtins.float | None = ...,
        longitude: builtins.float | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_latitude", b"_latitude", "_longitude", b"_longitude", "latitude", b"latitude", "longitude", b"longitude"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_latitude", b"_latitude", "_longitude", b"_longitude", "age", b"age", "bio", b"bio", "city", b"city", "gender", b"gender", "latitude", b"latitude", "longitude", b"longitude", "name", b"name", "telegram_id", b"telegram_id"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_latitude", b"_latitude"]) -> typing.Literal["latitude"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_longitude", b"_longitude"]) -> typing.Literal["longitude"] | None: ...

Global___CreateProfileRequest: typing_extensions.TypeAlias = CreateProfileRequest

@typing.final
class CreateProfileResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROFILE_ID_FIELD_NUMBER: builtins.int
    profile_id: builtins.int
    def __init__(
        self,
        *,
        profile_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["profile_id", b"profile_id"]) -> None: ...

Global___CreateProfileResponse: typing_extensions.TypeAlias = CreateProfileResponse

@typing.final
class GetProfileRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TELEGRAM_ID_FIELD_NUMBER: builtins.int
    telegram_id: builtins.int
    def __init__(
        self,
        *,
        telegram_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["telegram_id", b"telegram_id"]) -> None: ...

Global___GetProfileRequest: typing_extensions.TypeAlias = GetProfileRequest

@typing.final
class GetProfileResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FOUND_FIELD_NUMBER: builtins.int
    PROFILE_ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    AGE_FIELD_NUMBER: builtins.int
    CITY_FIELD_NUMBER: builtins.int
    BIO_FIELD_NUMBER: builtins.int
    GENDER_FIELD_NUMBER: builtins.int
    PHOTOS_FIELD_NUMBER: builtins.int
    LATITUDE_FIELD_NUMBER: builtins.int
    LONGITUDE_FIELD_NUMBER: builtins.int
    found: builtins.bool
    profile_id: builtins.int
    name: builtins.str
    age: builtins.int
    city: builtins.str
    bio: builtins.str
    gender: Global___Gender.ValueType
    latitude: builtins.float
    longitude: builtins.float
    @property
    def photos(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___PhotoInfo]: ...
    def __init__(
        self,
        *,
        found: builtins.bool = ...,
        profile_id: builtins.int = ...,
        name: builtins.str = ...,
        age: builtins.int = ...,
        city: builtins.str = ...,
        bio: builtins.str = ...,
        gender: Global___Gender.ValueType = ...,
        photos: collections.abc.Iterable[Global___PhotoInfo] | None = ...,
        latitude: builtins.float | None = ...,
        longitude: builtins.float | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_latitude", b"_latitude", "_longitude", b"_longitude", "latitude", b"latitude", "longitude", b"longitude"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_latitude", b"_latitude", "_longitude", b"_longitude", "age", b"age", "bio", b"bio", "city", b"city", "found", b"found", "gender", b"gender", "latitude", b"latitude", "longitude", b"longitude", "name", b"name", "photos", b"photos", "profile_id", b"profile_id"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_latitude", b"_latitude"]) -> typing.Literal["latitude"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_longitude", b"_longitude"]) -> typing.Literal["longitude"] | None: ...

Global___GetProfileResponse: typing_extensions.TypeAlias = GetProfileResponse

@typing.final
class GetProfileByIdRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROFILE_ID_FIELD_NUMBER: builtins.int
    profile_id: builtins.int
    def __init__(
        self,
        *,
        profile_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["profile_id", b"profile_id"]) -> None: ...

Global___GetProfileByIdRequest: typing_extensions.TypeAlias = GetProfileByIdRequest

@typing.final
class GetProfileByIdResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FOUND_FIELD_NUMBER: builtins.int
    PROFILE_ID_FIELD_NUMBER: builtins.int
    TELEGRAM_ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    AGE_FIELD_NUMBER: builtins.int
    CITY_FIELD_NUMBER: builtins.int
    BIO_FIELD_NUMBER: builtins.int
    GENDER_FIELD_NUMBER: builtins.int
    LATITUDE_FIELD_NUMBER: builtins.int
    LONGITUDE_FIELD_NUMBER: builtins.int
    IS_ACTIVE_FIELD_NUMBER: builtins.int
    BOOST_EXPIRES_AT_SECONDS_FIELD_NUMBER: builtins.int
    found: builtins.bool
    profile_id: builtins.int
    telegram_id: builtins.int
    name: builtins.str
    age: builtins.int
    city: builtins.str
    bio: builtins.str
    gender: Global___Gender.ValueType
    latitude: builtins.float
    longitude: builtins.float
    is_active: builtins.bool
    boost_expires_at_seconds: builtins.int
    def __init__(
        self,
        *,
        found: builtins.bool = ...,
        profile_id: builtins.int = ...,
        telegram_id: builtins.int = ...,
        name: builtins.str = ...,
        age: builtins.int = ...,
        city: builtins.str = ...,
        bio: builtins.str = ...,
        gender: Global___Gender.ValueType = ...,
        latitude: builtins.float | None = ...,
        longitude: builtins.float | None = ...,
        is_active: builtins.bool = ...,
        boost_expires_at_seconds: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_latitude", b"_latitude", "_longitude", b"_longitude", "latitude", b"latitude", "longitude", b"longitude"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_latitude", b"_latitude", "_longitude", b"_longitude", "age", b"age", "bio", b"bio", "boost_expires_at_seconds", b"boost_expires_at_seconds", "city", b"city", "found", b"found", "gender", b"gender", "is_active", b"is_active", "latitude", b"latitude", "longitude", b"longitude", "name", b"name", "profile_id", b"profile_id", "telegram_id", b"telegram_id"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_latitude", b"_latitude"]) -> typing.Literal["latitude"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_longitude", b"_longitude"]) -> typing.Literal["longitude"] | None: ...

Global___GetProfileByIdResponse: typing_extensions.TypeAlias = GetProfileByIdResponse

@typing.final
class PhotoInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PHOTO_ID_FIELD_NUMBER: builtins.int
    IS_ACTIVE_FIELD_NUMBER: builtins.int
    photo_id: builtins.int
    is_active: builtins.bool
    def __init__(
        self,
        *,
        photo_id: builtins.int = ...,
        is_active: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["is_active", b"is_active", "photo_id", b"photo_id"]) -> None: ...

Global___PhotoInfo: typing_extensions.TypeAlias = PhotoInfo

@typing.final
class UpdateProfileRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TELEGRAM_ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    AGE_FIELD_NUMBER: builtins.int
    CITY_FIELD_NUMBER: builtins.int
    BIO_FIELD_NUMBER: builtins.int
    telegram_id: builtins.int
    name: builtins.str
    age: builtins.int
    city: builtins.str
    bio: builtins.str
    def __init__(
        self,
        *,
        telegram_id: builtins.int = ...,
        name: builtins.str = ...,
        age: builtins.int = ...,
        city: builtins.str = ...,
        bio: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["age", b"age", "bio", b"bio", "city", b"city", "name", b"name", "telegram_id", b"telegram_id"]) -> None: ...

Global___UpdateProfileRequest: typing_extensions.TypeAlias = UpdateProfileRequest

@typing.final
class UpdateProfileResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    success: builtins.bool
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["success", b"success"]) -> None: ...

Global___UpdateProfileResponse: typing_extensions.TypeAlias = UpdateProfileResponse

@typing.final
class SetGeoRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TELEGRAM_ID_FIELD_NUMBER: builtins.int
    LATITUDE_FIELD_NUMBER: builtins.int
    LONGITUDE_FIELD_NUMBER: builtins.int
    telegram_id: builtins.int
    latitude: builtins.float
    longitude: builtins.float
    def __init__(
        self,
        *,
        telegram_id: builtins.int = ...,
        latitude: builtins.float = ...,
        longitude: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["latitude", b"latitude", "longitude", b"longitude", "telegram_id", b"telegram_id"]) -> None: ...

Global___SetGeoRequest: typing_extensions.TypeAlias = SetGeoRequest

@typing.final
class SetGeoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    success: builtins.bool
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["success", b"success"]) -> None: ...

Global___SetGeoResponse: typing_extensions.TypeAlias = SetGeoResponse

@typing.final
class UploadPhotoRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TELEGRAM_ID_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    CONTENT_TYPE_FIELD_NUMBER: builtins.int
    telegram_id: builtins.int
    data: builtins.bytes
    content_type: builtins.str
    def __init__(
        self,
        *,
        telegram_id: builtins.int = ...,
        data: builtins.bytes = ...,
        content_type: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["content_type", b"content_type", "data", b"data", "telegram_id", b"telegram_id"]) -> None: ...

Global___UploadPhotoRequest: typing_extensions.TypeAlias = UploadPhotoRequest

@typing.final
class UploadPhotoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PHOTO_ID_FIELD_NUMBER: builtins.int
    MINIO_KEY_FIELD_NUMBER: builtins.int
    photo_id: builtins.int
    minio_key: builtins.str
    def __init__(
        self,
        *,
        photo_id: builtins.int = ...,
        minio_key: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["minio_key", b"minio_key", "photo_id", b"photo_id"]) -> None: ...

Global___UploadPhotoResponse: typing_extensions.TypeAlias = UploadPhotoResponse

@typing.final
class DeletePhotoRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TELEGRAM_ID_FIELD_NUMBER: builtins.int
    PHOTO_ID_FIELD_NUMBER: builtins.int
    telegram_id: builtins.int
    photo_id: builtins.int
    def __init__(
        self,
        *,
        telegram_id: builtins.int = ...,
        photo_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["photo_id", b"photo_id", "telegram_id", b"telegram_id"]) -> None: ...

Global___DeletePhotoRequest: typing_extensions.TypeAlias = DeletePhotoRequest

@typing.final
class DeletePhotoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    success: builtins.bool
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["success", b"success"]) -> None: ...

Global___DeletePhotoResponse: typing_extensions.TypeAlias = DeletePhotoResponse

@typing.final
class GetPresignedUrlRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PHOTO_ID_FIELD_NUMBER: builtins.int
    photo_id: builtins.int
    def __init__(
        self,
        *,
        photo_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["photo_id", b"photo_id"]) -> None: ...

Global___GetPresignedUrlRequest: typing_extensions.TypeAlias = GetPresignedUrlRequest

@typing.final
class GetPresignedUrlResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URL_FIELD_NUMBER: builtins.int
    url: builtins.str
    def __init__(
        self,
        *,
        url: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["url", b"url"]) -> None: ...

Global___GetPresignedUrlResponse: typing_extensions.TypeAlias = GetPresignedUrlResponse

@typing.final
class SetPreferencesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TELEGRAM_ID_FIELD_NUMBER: builtins.int
    AGE_MIN_FIELD_NUMBER: builtins.int
    AGE_MAX_FIELD_NUMBER: builtins.int
    GENDER_PREF_FIELD_NUMBER: builtins.int
    MAX_DISTANCE_KM_FIELD_NUMBER: builtins.int
    telegram_id: builtins.int
    age_min: builtins.int
    age_max: builtins.int
    gender_pref: Global___GenderPref.ValueType
    max_distance_km: builtins.int
    def __init__(
        self,
        *,
        telegram_id: builtins.int = ...,
        age_min: builtins.int = ...,
        age_max: builtins.int = ...,
        gender_pref: Global___GenderPref.ValueType = ...,
        max_distance_km: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["age_max", b"age_max", "age_min", b"age_min", "gender_pref", b"gender_pref", "max_distance_km", b"max_distance_km", "telegram_id", b"telegram_id"]) -> None: ...

Global___SetPreferencesRequest: typing_extensions.TypeAlias = SetPreferencesRequest

@typing.final
class SetPreferencesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    success: builtins.bool
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["success", b"success"]) -> None: ...

Global___SetPreferencesResponse: typing_extensions.TypeAlias = SetPreferencesResponse

@typing.final
class GetPreferencesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TELEGRAM_ID_FIELD_NUMBER: builtins.int
    telegram_id: builtins.int
    def __init__(
        self,
        *,
        telegram_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["telegram_id", b"telegram_id"]) -> None: ...

Global___GetPreferencesRequest: typing_extensions.TypeAlias = GetPreferencesRequest

@typing.final
class GetPreferencesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FOUND_FIELD_NUMBER: builtins.int
    AGE_MIN_FIELD_NUMBER: builtins.int
    AGE_MAX_FIELD_NUMBER: builtins.int
    GENDER_PREF_FIELD_NUMBER: builtins.int
    MAX_DISTANCE_KM_FIELD_NUMBER: builtins.int
    found: builtins.bool
    age_min: builtins.int
    age_max: builtins.int
    gender_pref: Global___GenderPref.ValueType
    max_distance_km: builtins.int
    def __init__(
        self,
        *,
        found: builtins.bool = ...,
        age_min: builtins.int = ...,
        age_max: builtins.int = ...,
        gender_pref: Global___GenderPref.ValueType = ...,
        max_distance_km: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["age_max", b"age_max", "age_min", b"age_min", "found", b"found", "gender_pref", b"gender_pref", "max_distance_km", b"max_distance_km"]) -> None: ...

Global___GetPreferencesResponse: typing_extensions.TypeAlias = GetPreferencesResponse
