"""
@generated by mypy-protobuf. Do not edit manually!
Run `just generate-profile-api` to regenerate.
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor


class _Gender:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _GenderEnumTypeWrapper(
    google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Gender.ValueType],
    builtins.type,
):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    GENDER_UNSPECIFIED: _Gender.ValueType  # 0
    GENDER_MALE: _Gender.ValueType  # 1
    GENDER_FEMALE: _Gender.ValueType  # 2


class Gender(_Gender, metaclass=_GenderEnumTypeWrapper): ...


GENDER_UNSPECIFIED: Gender.ValueType  # 0
GENDER_MALE: Gender.ValueType  # 1
GENDER_FEMALE: Gender.ValueType  # 2
Global___Gender: typing_extensions.TypeAlias = Gender


@typing.final
class HealthRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None: ...


Global___HealthRequest: typing_extensions.TypeAlias = HealthRequest


@typing.final
class HealthResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OK_FIELD_NUMBER: builtins.int
    ok: builtins.bool

    def __init__(self, *, ok: builtins.bool = ...) -> None: ...
    def ClearField(self, field_name: typing.Literal["ok", b"ok"]) -> None: ...


Global___HealthResponse: typing_extensions.TypeAlias = HealthResponse


@typing.final
class CreateProfileRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TELEGRAM_ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    AGE_FIELD_NUMBER: builtins.int
    CITY_FIELD_NUMBER: builtins.int
    BIO_FIELD_NUMBER: builtins.int
    GENDER_FIELD_NUMBER: builtins.int
    telegram_id: builtins.int
    name: builtins.str
    age: builtins.int
    city: builtins.str
    bio: builtins.str
    gender: Global___Gender.ValueType

    def __init__(
        self,
        *,
        telegram_id: builtins.int = ...,
        name: builtins.str = ...,
        age: builtins.int = ...,
        city: builtins.str = ...,
        bio: builtins.str = ...,
        gender: Global___Gender.ValueType = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "telegram_id", b"telegram_id", "name", b"name", "age", b"age",
            "city", b"city", "bio", b"bio", "gender", b"gender",
        ],
    ) -> None: ...


Global___CreateProfileRequest: typing_extensions.TypeAlias = CreateProfileRequest


@typing.final
class CreateProfileResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROFILE_ID_FIELD_NUMBER: builtins.int
    profile_id: builtins.int

    def __init__(self, *, profile_id: builtins.int = ...) -> None: ...
    def ClearField(self, field_name: typing.Literal["profile_id", b"profile_id"]) -> None: ...


Global___CreateProfileResponse: typing_extensions.TypeAlias = CreateProfileResponse


@typing.final
class GetProfileRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TELEGRAM_ID_FIELD_NUMBER: builtins.int
    telegram_id: builtins.int

    def __init__(self, *, telegram_id: builtins.int = ...) -> None: ...
    def ClearField(self, field_name: typing.Literal["telegram_id", b"telegram_id"]) -> None: ...


Global___GetProfileRequest: typing_extensions.TypeAlias = GetProfileRequest


@typing.final
class PhotoInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PHOTO_ID_FIELD_NUMBER: builtins.int
    IS_ACTIVE_FIELD_NUMBER: builtins.int
    photo_id: builtins.int
    is_active: builtins.bool

    def __init__(self, *, photo_id: builtins.int = ..., is_active: builtins.bool = ...) -> None: ...
    def ClearField(
        self, field_name: typing.Literal["photo_id", b"photo_id", "is_active", b"is_active"]
    ) -> None: ...


Global___PhotoInfo: typing_extensions.TypeAlias = PhotoInfo


@typing.final
class GetProfileResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FOUND_FIELD_NUMBER: builtins.int
    PROFILE_ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    AGE_FIELD_NUMBER: builtins.int
    CITY_FIELD_NUMBER: builtins.int
    BIO_FIELD_NUMBER: builtins.int
    GENDER_FIELD_NUMBER: builtins.int
    PHOTOS_FIELD_NUMBER: builtins.int
    found: builtins.bool
    profile_id: builtins.int
    name: builtins.str
    age: builtins.int
    city: builtins.str
    bio: builtins.str
    gender: Global___Gender.ValueType

    @property
    def photos(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___PhotoInfo]: ...
    def __init__(
        self,
        *,
        found: builtins.bool = ...,
        profile_id: builtins.int = ...,
        name: builtins.str = ...,
        age: builtins.int = ...,
        city: builtins.str = ...,
        bio: builtins.str = ...,
        gender: Global___Gender.ValueType = ...,
        photos: collections.abc.Iterable[Global___PhotoInfo] | None = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "found", b"found", "profile_id", b"profile_id", "name", b"name",
            "age", b"age", "city", b"city", "bio", b"bio", "gender", b"gender", "photos", b"photos",
        ],
    ) -> None: ...


Global___GetProfileResponse: typing_extensions.TypeAlias = GetProfileResponse


@typing.final
class UpdateProfileRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TELEGRAM_ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    AGE_FIELD_NUMBER: builtins.int
    CITY_FIELD_NUMBER: builtins.int
    BIO_FIELD_NUMBER: builtins.int
    telegram_id: builtins.int
    name: builtins.str
    age: builtins.int
    city: builtins.str
    bio: builtins.str

    def __init__(
        self,
        *,
        telegram_id: builtins.int = ...,
        name: builtins.str = ...,
        age: builtins.int = ...,
        city: builtins.str = ...,
        bio: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "telegram_id", b"telegram_id", "name", b"name", "age", b"age", "city", b"city", "bio", b"bio",
        ],
    ) -> None: ...


Global___UpdateProfileRequest: typing_extensions.TypeAlias = UpdateProfileRequest


@typing.final
class UpdateProfileResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    success: builtins.bool

    def __init__(self, *, success: builtins.bool = ...) -> None: ...
    def ClearField(self, field_name: typing.Literal["success", b"success"]) -> None: ...


Global___UpdateProfileResponse: typing_extensions.TypeAlias = UpdateProfileResponse


@typing.final
class UploadPhotoRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TELEGRAM_ID_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    CONTENT_TYPE_FIELD_NUMBER: builtins.int
    telegram_id: builtins.int
    data: builtins.bytes
    content_type: builtins.str

    def __init__(
        self,
        *,
        telegram_id: builtins.int = ...,
        data: builtins.bytes = ...,
        content_type: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "telegram_id", b"telegram_id", "data", b"data", "content_type", b"content_type",
        ],
    ) -> None: ...


Global___UploadPhotoRequest: typing_extensions.TypeAlias = UploadPhotoRequest


@typing.final
class UploadPhotoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PHOTO_ID_FIELD_NUMBER: builtins.int
    MINIO_KEY_FIELD_NUMBER: builtins.int
    photo_id: builtins.int
    minio_key: builtins.str

    def __init__(self, *, photo_id: builtins.int = ..., minio_key: builtins.str = ...) -> None: ...
    def ClearField(
        self, field_name: typing.Literal["photo_id", b"photo_id", "minio_key", b"minio_key"]
    ) -> None: ...


Global___UploadPhotoResponse: typing_extensions.TypeAlias = UploadPhotoResponse


@typing.final
class GetPresignedUrlRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PHOTO_ID_FIELD_NUMBER: builtins.int
    photo_id: builtins.int

    def __init__(self, *, photo_id: builtins.int = ...) -> None: ...
    def ClearField(self, field_name: typing.Literal["photo_id", b"photo_id"]) -> None: ...


Global___GetPresignedUrlRequest: typing_extensions.TypeAlias = GetPresignedUrlRequest


@typing.final
class GetPresignedUrlResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URL_FIELD_NUMBER: builtins.int
    url: builtins.str

    def __init__(self, *, url: builtins.str = ...) -> None: ...
    def ClearField(self, field_name: typing.Literal["url", b"url"]) -> None: ...


Global___GetPresignedUrlResponse: typing_extensions.TypeAlias = GetPresignedUrlResponse
